# Generated by Django 4.2.3 on 2023-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_id_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/path/to/default_image.jpg', upload_to='post_images/'),
        ),
    ]
